### ISSUE TITLE
Ready to merge/implemented PRs

### ISSUE THREAD

**Issue by arobsn** [ergoplatform/eips#86]
In the following I'm putting together a list of old PRs which are already implemented but not yet merged. Would be good if we can take a look and take actions to get them merged.

# Ready to merge?
- [ ] #8 - Implemented, 1 approval
- [x] #74 - Rolled back, approved
- [ ] #79 - Implemented, approved

# Waiting review
- [ ] #11 - Implemented, waiting review
- [ ] #12 - Implemented, waiting review
- [ ] #27 - Implemented, not clear if requested changes are made
- [ ] #29 - Implemented, would be good if we get this reviewed and merged
- [ ] #53 - Implemented, waiting review

**Comment by MrStahlfelge** [comment]
Waiting for review as well: #53 ErgoAuth

**Comment by arobsn** [comment]
> Waiting for review as well: #53 ErgoAuth

Oh true, Included!
